title: Test Site Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jfkoehler.github.io/test_site

aux_links:
  Template Repository: https://github.com/jfkoehler/test_site_jekyll
